"""Stateful mock sandbox executor (V2 §26). Tier: mock (default).

Realistic state transitions per action; reads produce zero diff. RED/denied
actions NEVER reach apply() — the FSM/executor gate (Step 22) enforces
validator+policy+HITL first; apply() asserts the action is allowlisted.
Docker/Kind tiers later reuse the same Action schema.
"""
from __future__ import annotations

import copy
import sys
import uuid
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "backend"))

from app.schemas import Action, Execution  # noqa: E402

READ_TYPES = {"read", "describe", "logs", "metrics", "list"}
MOCKABLE = READ_TYPES | {"restart_pod", "scale_deployment", "rolling_restart",
                         "rollback_deployment", "patch_config"}


def initial_state(service: str = "web", version: str = "v23",
                  error_rate: float = 0.18) -> dict[str, Any]:
    return {"service": service, "deployment_version": version,
            "replicas": 3, "error_rate": error_rate, "pods_ready": True,
            "restarts": 0, "config_rev": "c1"}


def apply(action: Action, state: dict[str, Any]) -> tuple[Execution, dict]:
    """Apply an AUTHORIZED action. Returns (execution, new_state)."""
    if action.action_type not in MOCKABLE:
        raise ValueError(f"not executable in mock tier: {action.action_type}")
    before = copy.deepcopy(state)
    after = copy.deepcopy(state)
    logs = [f"mock-exec {action.action_type} {action.resource_id}"]
    p = action.parameters

    if action.action_type == "rollback_deployment":
        after["deployment_version"] = str(p.get("to_version", "v22"))
        after["error_rate"] = 0.008
        logs.append(f"rolled back to {after['deployment_version']}")
    elif action.action_type == "restart_pod":
        after["restarts"] = int(state.get("restarts", 0)) + 1
        after["pods_ready"] = True
    elif action.action_type == "scale_deployment":
        after["replicas"] = int(p.get("replicas", state.get("replicas", 3)))
    elif action.action_type == "rolling_restart":
        after["restarts"] = int(state.get("restarts", 0)) + 1
        after["error_rate"] = round(float(state.get("error_rate", 0)) * 0.5, 4)
    elif action.action_type == "patch_config":
        after["config_rev"] = "c2"
    # reads: no mutation

    diff = {k: {"before": before.get(k), "after": after.get(k)}
            for k in after if before.get(k) != after.get(k)}
    exe = Execution(action_id=action.action_id, incident_id=action.incident_id,
                    tier="mock", state_diff={"before": before, "after": after,
                                             "changed": diff},
                    logs=logs, idempotency_key=action.action_id)
    _ = uuid.uuid4()  # execution_id auto-generated by schema
    return exe, after
